version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - unified-services
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: imv_crm
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306" # Mapped to localhost only for security

  backend:
    build: ./backend
    restart: always
    ports:
      - "3010:3010"
    networks:
      - unified-services
    environment:
      - PORT=3010
      - DB_HOST=imv_crm-db-1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=imv_crm
      - JWT_SECRET=7861295b154a5b660fdf0ae93dbb8654c363aa026c2cda3d41782cb0d4df6ebd28f42752698a281ff88dd10ae590ec3d
      - N8N_API_KEY=d927994f95870a3ad2a57fa70d0b767dfd273692dd23324f449e9cecffe9dc8b
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: always
    ports:
      - "8095:80" 
    networks:
      - unified-services
    depends_on:
      - backend

volumes:
  db_data:

networks:
  unified-services:
    name: imv_crm_unified-services
    external: true

